#!/usr/bin/env python3
"""Post-process AIMLT-2606 Module 1: merge mental maps, alias files, add missing lectures."""

from pathlib import Path

BATCH = Path(__file__).resolve().parent / "IITP-AIMLT-2606" / "Module 1- Foundations of Data"

PLACEHOLDER = """## Mental Map

*(Generated by mental-map script — see mental Map file in this folder.)*"""

LECTURES = {
    "Session 9- NumPy- Numerical Foundation": (
        "NumPy - Numerical Foundation",
        """# Lecture Script: NumPy — Numerical Foundation
> **Instructor Reference** — Module 1: Foundations of Data | Session 9 | Duration: 2 Hours

---

## Session Overview

**Goal:** Students create and manipulate NumPy arrays with indexing, slicing, broadcasting, reshape, and flatten — without Python loops.

**Key outcome:** Vectorized temperature and sales calculations on 1D and 2D arrays.

---

## Timing Breakdown

| Segment | Duration |
|---|---|
| Why NumPy after lists | 10 min |
| Create arrays, dtype, shape | 20 min |
| Indexing & slicing | 20 min |
| BREAK | 10 min |
| Element-wise ops & broadcasting | 25 min |
| reshape, flatten, 2D arrays | 20 min |
| Lab: array stats challenge | 10 min |
| Wrap | 5 min |

---

## Live Demo Sequence

```python
import numpy as np
a = np.array([1, 2, 3, 4])
print(a * 2, a.mean())

m = np.array([[1, 2], [3, 4]])
print(m.shape, m.flatten())
```

Emphasise: same operation on whole array — no for-loop.
""",
    ),
    "Session 10- Pandas- Loading, Inspection & Filtering": (
        "Pandas - Loading, Inspection & Filtering",
        """# Lecture Script: Pandas — Loading, Inspection & Filtering
> **Instructor Reference** — Module 1: Foundations of Data | Session 10 | Duration: 2 Hours

---

## Session Overview

**Goal:** Load CSVs, inspect with head/info/describe, filter with boolean indexing and loc/iloc.

**Key outcome:** Clean exploration report on a messy employee or sales CSV.

---

## Timing Breakdown

| Segment | Duration |
|---|---|
| Series vs DataFrame | 15 min |
| read_csv + inspection trio | 25 min |
| Boolean filtering | 20 min |
| BREAK | 10 min |
| loc vs iloc | 25 min |
| Sorting & column selection | 15 min |
| Lab: find data quality issues | 15 min |
| Wrap | 5 min |

---

## Inspection checklist (teach as ritual)

```python
import pandas as pd
df = pd.read_csv("data.csv")
df.head()
df.info()
df.describe()
df.shape
```
""",
    ),
    "Session 11- Pandas- Aggregation, Groupby & Merging": (
        "Pandas - Aggregation, Groupby & Merging",
        """# Lecture Script: Pandas — Aggregation, Groupby & Merging
> **Instructor Reference** — Module 1: Foundations of Data | Session 11 | Duration: 2 Hours

---

## Session Overview

**Goal:** Answer business questions with groupby/agg, handle missing values, merge and concat tables.

**Key outcome:** Department salary report + merged customer-orders dataset.

---

## Timing Breakdown

| Segment | Duration |
|---|---|
| groupby mental model | 15 min |
| agg, value_counts | 20 min |
| fillna / dropna strategies | 20 min |
| BREAK | 10 min |
| merge types (inner/left) | 25 min |
| concat & drop_duplicates | 15 min |
| Lab: end-to-end mini analysis | 10 min |
| Wrap | 5 min |

---

## Key teaching line

Split-apply-combine: split by key → apply function → combine results into summary table.
""",
    ),
    "Session 16- Data Analysis with Spreadsheets": (
        "Data Analysis with Spreadsheets",
        """# Lecture Script: Data Analysis with Spreadsheets
> **Instructor Reference** — Module 1: Foundations of Data | Session 16 | Duration: 2 Hours

---

## Session Overview

**Goal:** Students use Excel/Sheets for VLOOKUP/XLOOKUP, pivot tables, COUNTIF, and conditional formatting — as a complement to Python/SQL.

**Key outcome:** Build a one-sheet sales dashboard from two related tables without code.

---

## Timing Breakdown

| Segment | Duration |
|---|---|
| When spreadsheets vs code/SQL | 10 min |
| XLOOKUP / VLOOKUP live | 25 min |
| Pivot tables | 25 min |
| BREAK | 10 min |
| COUNTIF, basic formulas | 20 min |
| Conditional formatting | 15 min |
| Lab: regional sales summary | 10 min |
| Module 1 recap | 5 min |

---

## Bridge to the course

Spreadsheets, SQL, and Pandas share the same logic — filter, aggregate, join. Module 2 starts ML on clean tables you now know how to prepare.
""",
    ),
}


def merge_mental_maps() -> None:
    for folder in sorted(BATCH.iterdir()):
        if not folder.is_dir() or not folder.name.startswith("Session"):
            continue
        mental_files = list(folder.glob("mental Map: *.md"))
        pre_files = list(folder.glob("pre-read: *.md"))
        if not mental_files or not pre_files:
            continue
        mental = mental_files[0].read_text(encoding="utf-8").strip()
        pre = pre_files[0].read_text(encoding="utf-8")
        label = pre_files[0].name.replace("pre-read: ", "").replace(".md", "")

        if PLACEHOLDER in pre:
            pre = pre.replace(PLACEHOLDER, f"## Mental Map\n\n{mental}")
        elif "## Mental Map" in pre and "flowchart" not in pre.split("## What You'll Learn")[0]:
            # Copied pre-reads may already have old mental map — replace section
            parts = pre.split("## What You'll Learn", 1)
            header = parts[0].split("---", 1)[0] + "---\n\n"
            pre = header + f"## Mental Map\n\n{mental}\n\n## What You'll Learn" + parts[1]

        pre_files[0].write_text(pre, encoding="utf-8")

        alias = folder / f"mental-map: {label}.md"
        alias.write_text(mental + "\n", encoding="utf-8")


def add_lectures() -> None:
    for folder_name, (label, content) in LECTURES.items():
        folder = BATCH / folder_name
        path = folder / f"lecture-script: {label}.md"
        if not path.exists():
            path.write_text(content.strip() + "\n", encoding="utf-8")
            print(f"Added lecture: {folder_name}")


def main() -> None:
    merge_mental_maps()
    add_lectures()
    print("Post-process complete.")


if __name__ == "__main__":
    main()
